// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"FrontEnd/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/rpc/getSupportTargetFormatsSourceFormat",
				Handler: getSupportTargetFormatsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasksConversion",
				Handler: addTaskHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthByTaskToken},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/files/:fileId",
					Handler: getFileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tasks/:taskId",
					Handler: getTaskHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
