rust_library(
    name = "shared-types",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "root//third-party/rust:buffa",
        "root//third-party/rust:buffa-types",
        "root//third-party/rust:connectrpc",
        "root//third-party/rust:serde",
        "root//third-party/rust:serde_json",
    ],
)
