extra_srcs = [
    "src/data/alg-ecdsa-p256.der",
    "src/data/alg-ecdsa-p256k1.der",
    "src/data/alg-ecdsa-p384.der",
    "src/data/alg-ecdsa-p521.der",
    "src/data/alg-ecdsa-sha256.der",
    "src/data/alg-ecdsa-sha384.der",
    "src/data/alg-ecdsa-sha512.der",
    "src/data/alg-ed25519.der",
    "src/data/alg-ed448.der",
    "src/data/alg-ml-dsa-44.der",
    "src/data/alg-ml-dsa-65.der",
    "src/data/alg-ml-dsa-87.der",
    "src/data/alg-rsa-encryption.der",
    "src/data/alg-rsa-pkcs1-sha256.der",
    "src/data/alg-rsa-pkcs1-sha384.der",
    "src/data/alg-rsa-pkcs1-sha512.der",
    "src/data/alg-rsa-pss-sha256.der",
    "src/data/alg-rsa-pss-sha384.der",
    "src/data/alg-rsa-pss-sha512.der",
]
