extra_srcs = [
    "README.md",
    "tests/examples/pkcs1/rsa2048-priv.der",
    "tests/examples/pkcs1/rsa2048-priv.pem",
    "tests/examples/pkcs1/rsa2048-pub.der",
    "tests/examples/pkcs1/rsa2048-pub.pem",
    "tests/examples/pkcs1/rsa4096-priv.der",
    "tests/examples/pkcs1/rsa4096-priv.pem",
    "tests/examples/pkcs1/rsa4096-pub.der",
    "tests/examples/pkcs1/rsa4096-pub.pem",
    "tests/examples/pkcs8/rsa2048-priv.der",
    "tests/examples/pkcs8/rsa2048-priv.pem",
    "tests/examples/pkcs8/rsa2048-pub.der",
    "tests/examples/pkcs8/rsa2048-pub.pem",
]
