extra_srcs = [
    "README.md",
    "examples/cargo-example-derive.md",
    "examples/cargo-example-derive.rs",
    "examples/cargo-example.md",
    "examples/cargo-example.rs",
    "examples/demo.md",
    "examples/demo.rs",
    "examples/escaped-positional-derive.md",
    "examples/escaped-positional-derive.rs",
    "examples/escaped-positional.md",
    "examples/escaped-positional.rs",
    "examples/find.md",
    "examples/find.rs",
    "examples/git-derive.md",
    "examples/git-derive.rs",
    "examples/git.md",
    "examples/git.rs",
    "examples/multicall-busybox.md",
    "examples/multicall-busybox.rs",
    "examples/multicall-hostname.md",
    "examples/multicall-hostname.rs",
    "examples/pacman.md",
    "examples/pacman.rs",
    "examples/repl-derive.rs",
    "examples/repl.rs",
    "examples/tutorial_builder/01_quick.md",
    "examples/tutorial_builder/01_quick.rs",
    "examples/tutorial_builder/02_app_settings.md",
    "examples/tutorial_builder/02_app_settings.rs",
    "examples/tutorial_builder/02_apps.md",
    "examples/tutorial_builder/02_apps.rs",
    "examples/tutorial_builder/02_crate.md",
    "examples/tutorial_builder/02_crate.rs",
    "examples/tutorial_builder/03_01_flag_bool.md",
    "examples/tutorial_builder/03_01_flag_bool.rs",
    "examples/tutorial_builder/03_01_flag_count.md",
    "examples/tutorial_builder/03_01_flag_count.rs",
    "examples/tutorial_builder/03_02_option.md",
    "examples/tutorial_builder/03_02_option.rs",
    "examples/tutorial_builder/03_02_option_mult.md",
    "examples/tutorial_builder/03_02_option_mult.rs",
    "examples/tutorial_builder/03_03_positional.md",
    "examples/tutorial_builder/03_03_positional.rs",
    "examples/tutorial_builder/03_03_positional_mult.md",
    "examples/tutorial_builder/03_03_positional_mult.rs",
    "examples/tutorial_builder/03_04_subcommands.md",
    "examples/tutorial_builder/03_04_subcommands.rs",
    "examples/tutorial_builder/03_05_default_values.md",
    "examples/tutorial_builder/03_05_default_values.rs",
    "examples/tutorial_builder/03_06_required.md",
    "examples/tutorial_builder/03_06_required.rs",
    "examples/tutorial_builder/04_01_enum.md",
    "examples/tutorial_builder/04_01_enum.rs",
    "examples/tutorial_builder/04_01_possible.md",
    "examples/tutorial_builder/04_01_possible.rs",
    "examples/tutorial_builder/04_02_parse.md",
    "examples/tutorial_builder/04_02_parse.rs",
    "examples/tutorial_builder/04_02_validate.md",
    "examples/tutorial_builder/04_02_validate.rs",
    "examples/tutorial_builder/04_03_relations.md",
    "examples/tutorial_builder/04_03_relations.rs",
    "examples/tutorial_builder/04_04_custom.md",
    "examples/tutorial_builder/04_04_custom.rs",
    "examples/tutorial_builder/05_01_assert.rs",
    "examples/tutorial_derive/01_quick.md",
    "examples/tutorial_derive/01_quick.rs",
    "examples/tutorial_derive/02_app_settings.md",
    "examples/tutorial_derive/02_app_settings.rs",
    "examples/tutorial_derive/02_apps.md",
    "examples/tutorial_derive/02_apps.rs",
    "examples/tutorial_derive/02_crate.md",
    "examples/tutorial_derive/02_crate.rs",
    "examples/tutorial_derive/03_01_flag_bool.md",
    "examples/tutorial_derive/03_01_flag_bool.rs",
    "examples/tutorial_derive/03_01_flag_count.md",
    "examples/tutorial_derive/03_01_flag_count.rs",
    "examples/tutorial_derive/03_02_option.md",
    "examples/tutorial_derive/03_02_option.rs",
    "examples/tutorial_derive/03_02_option_mult.md",
    "examples/tutorial_derive/03_02_option_mult.rs",
    "examples/tutorial_derive/03_03_positional.md",
    "examples/tutorial_derive/03_03_positional.rs",
    "examples/tutorial_derive/03_03_positional_mult.md",
    "examples/tutorial_derive/03_03_positional_mult.rs",
    "examples/tutorial_derive/03_04_subcommands.md",
    "examples/tutorial_derive/03_04_subcommands.rs",
    "examples/tutorial_derive/03_04_subcommands_alt.rs",
    "examples/tutorial_derive/03_05_default_values.md",
    "examples/tutorial_derive/03_05_default_values.rs",
    "examples/tutorial_derive/03_06_optional.md",
    "examples/tutorial_derive/03_06_optional.rs",
    "examples/tutorial_derive/04_01_enum.md",
    "examples/tutorial_derive/04_01_enum.rs",
    "examples/tutorial_derive/04_02_parse.md",
    "examples/tutorial_derive/04_02_parse.rs",
    "examples/tutorial_derive/04_02_validate.md",
    "examples/tutorial_derive/04_02_validate.rs",
    "examples/tutorial_derive/04_03_relations.md",
    "examples/tutorial_derive/04_03_relations.rs",
    "examples/tutorial_derive/04_04_custom.md",
    "examples/tutorial_derive/04_04_custom.rs",
    "examples/tutorial_derive/05_01_assert.rs",
    "examples/typed-derive/builtin.md",
    "examples/typed-derive/builtin.rs",
    "examples/typed-derive/custom.md",
    "examples/typed-derive/custom.rs",
    "examples/typed-derive/fn_parser.md",
    "examples/typed-derive/fn_parser.rs",
    "examples/typed-derive/implicit.md",
    "examples/typed-derive/implicit.rs",
]
