// Code generated by goctl. DO NOT EDIT.
package types

type Conversion struct {
	Id           string `json:"id"`
	SourceFormat string `json:"sourceFormat"`
	TargetFormat string `json:"targetFormat"`
}

type File struct {
	Id  string `json:"id"`
	URL string `json:"url"`
}

type SourceFormat struct {
	SourceFormat string `json:"sourceFormat"`
}

type Task struct {
	Id             string `json:"id"`
	Status         string `json:"status"`
	SelectedWorker string `json:"selectedWorker"`
	Context        string `json:"context"`
}

type AddTaskResp struct {
	TaskAccessToken string `json:"taskAccessToken"`
	Task            Task   `json:"task"`
}
