extra_srcs = [
    "README.md",
    "tests/examples/rsa2048-priv-3prime.der",
    "tests/examples/rsa2048-priv.der",
    "tests/examples/rsa2048-priv.pem",
    "tests/examples/rsa2048-pub.der",
    "tests/examples/rsa2048-pub.pem",
    "tests/examples/rsa4096-priv.der",
    "tests/examples/rsa4096-pub.der",
    "tests/examples/rsa4096-pub.pem",
]
