extra_srcs = [
    "src/generated/google.protobuf.any.__view.rs",
    "src/generated/google.protobuf.any.rs",
    "src/generated/google.protobuf.duration.__view.rs",
    "src/generated/google.protobuf.duration.rs",
    "src/generated/google.protobuf.empty.__view.rs",
    "src/generated/google.protobuf.empty.rs",
    "src/generated/google.protobuf.field_mask.__view.rs",
    "src/generated/google.protobuf.field_mask.rs",
    "src/generated/google.protobuf.mod.rs",
    "src/generated/google.protobuf.struct.__oneof.rs",
    "src/generated/google.protobuf.struct.__view.rs",
    "src/generated/google.protobuf.struct.__view_oneof.rs",
    "src/generated/google.protobuf.struct.rs",
    "src/generated/google.protobuf.timestamp.__view.rs",
    "src/generated/google.protobuf.timestamp.rs",
    "src/generated/google.protobuf.wrappers.__view.rs",
    "src/generated/google.protobuf.wrappers.rs",
]
