extra_srcs = [
    "tests/cert_v1.der",
    "tests/cert_without_extensions.der",
    "tests/client_auth/cert_with_both_ekus_accepted_for_client_auth.ca.der",
    "tests/client_auth/cert_with_both_ekus_accepted_for_client_auth.ee.der",
    "tests/client_auth/cert_with_clientauth_eku_accepted_for_client_auth.ca.der",
    "tests/client_auth/cert_with_clientauth_eku_accepted_for_client_auth.ee.der",
    "tests/client_auth/cert_with_no_eku_accepted_for_client_auth.ca.der",
    "tests/client_auth/cert_with_no_eku_accepted_for_client_auth.ee.der",
    "tests/client_auth/cert_with_serverauth_eku_rejected_for_client_auth.ca.der",
    "tests/client_auth/cert_with_serverauth_eku_rejected_for_client_auth.ee.der",
    "tests/client_auth_revocation/ee_not_revoked_chain_depth.crl.der",
    "tests/client_auth_revocation/ee_not_revoked_ee_depth.crl.der",
    "tests/client_auth_revocation/no_ku_chain.ee.der",
    "tests/client_auth_revocation/no_ku_chain.int.a.ca.der",
    "tests/client_auth_revocation/no_ku_chain.int.b.ca.der",
    "tests/client_auth_revocation/no_ku_chain.root.ca.der",
    "tests/client_auth_revocation/no_relevant_crl_ee_depth_allow_unknown.crl.der",
    "tests/cloudflare_dns/ca.der",
    "tests/cloudflare_dns/ee.der",
    "tests/cloudflare_dns/inter.der",
    "tests/critical_extensions/ca-cert.der",
    "tests/critical_extensions/ee-cert-crit-unknown-ext.der",
    "tests/critical_extensions/ee-cert-noncrit-unknown-ext.der",
    "tests/critical_extensions/root-cert.der",
    "tests/crls/crl.delta.der",
    "tests/crls/crl.empty.der",
    "tests/crls/crl.entry.empty.ext.seq.der",
    "tests/crls/crl.entry.invalid.reason.der",
    "tests/crls/crl.entry.invalidity.date.der",
    "tests/crls/crl.entry.unknown.crit.ext.der",
    "tests/crls/crl.invalid.this.update.time.der",
    "tests/crls/crl.mismatched.sigalg.der",
    "tests/crls/crl.missing.exts.der",
    "tests/crls/crl.missing.next.update.der",
    "tests/crls/crl.negative.crl.number.der",
    "tests/crls/crl.negative.serial.der",
    "tests/crls/crl.no.entry.exts.der",
    "tests/crls/crl.too.long.crl.number.der",
    "tests/crls/crl.topbit.serial.der",
    "tests/crls/crl.unknown.crit.ext.der",
    "tests/crls/crl.valid.der",
    "tests/crls/crl.wrong.version.der",
    "tests/ed25519/ca.der",
    "tests/ed25519/ee-pubkey.der",
    "tests/ed25519/ee.der",
    "tests/misc/dns_names_and_wildcards.der",
    "tests/misc/invalid_subject_alternative_name.der",
    "tests/misc/mdoc_eku.ca.der",
    "tests/misc/mdoc_eku.ee.der",
    "tests/misc/no_subject_alternative_name.der",
    "tests/misc/serial_large_positive.der",
    "tests/misc/serial_neg.der",
    "tests/misc/serial_neg_ca.der",
    "tests/misc/serial_neg_ee.der",
    "tests/misc/serial_zero.der",
    "tests/netflix/ca.der",
    "tests/netflix/ee.der",
    "tests/netflix/inter.der",
    "tests/signatures/ecdsa_p256.ee.der",
    "tests/signatures/ecdsa_p256.spki.der",
    "tests/signatures/ecdsa_p256_key_and_ecdsa_p256_sha256_good_signature.sig.bin",
    "tests/signatures/ecdsa_p256_key_and_ecdsa_p256_sha384_good_signature.sig.bin",
    "tests/signatures/ed25519.ee.der",
    "tests/signatures/ed25519.spki.der",
    "tests/signatures/ed25519_key_and_ed25519_detects_bad_signature.sig.bin",
    "tests/signatures/ed25519_key_and_ed25519_good_signature.sig.bin",
    "tests/signatures/message.bin",
    "tests/tls_server_certs/additional_dns_labels.ca.der",
    "tests/tls_server_certs/additional_dns_labels.ee.der",
    "tests/tls_server_certs/allow_dns_san.ca.der",
    "tests/tls_server_certs/allow_dns_san.ee.der",
    "tests/tls_server_certs/allow_dns_san_and_subject_common_name.ca.der",
    "tests/tls_server_certs/allow_dns_san_and_subject_common_name.ee.der",
    "tests/tls_server_certs/allow_subject_common_name.ca.der",
    "tests/tls_server_certs/allow_subject_common_name.ee.der",
    "tests/tls_server_certs/disallow_dns_san.ca.der",
    "tests/tls_server_certs/disallow_dns_san.ee.der",
    "tests/tls_server_certs/disallow_dns_san_and_allow_subject_common_name.ca.der",
    "tests/tls_server_certs/disallow_dns_san_and_allow_subject_common_name.ee.der",
    "tests/tls_server_certs/ip46_mixed_address_san_allowed.ca.der",
    "tests/tls_server_certs/ip46_mixed_address_san_allowed.ee.der",
    "tests/tls_server_certs/ip4_address_san_allowed.ca.der",
    "tests/tls_server_certs/ip4_address_san_allowed.ee.der",
    "tests/tls_server_certs/ip4_address_san_rejected_if_in_excluded_subtree.ca.der",
    "tests/tls_server_certs/ip4_address_san_rejected_if_in_excluded_subtree.ee.der",
    "tests/tls_server_certs/ip6_address_san_allowed.ca.der",
    "tests/tls_server_certs/ip6_address_san_allowed.ee.der",
    "tests/tls_server_certs/ip6_address_san_rejected_if_in_excluded_subtree.ca.der",
    "tests/tls_server_certs/ip6_address_san_rejected_if_in_excluded_subtree.ee.der",
    "tests/tls_server_certs/no_name_constraints.ca.der",
    "tests/tls_server_certs/no_name_constraints.ee.der",
    "tests/tls_server_certs/reject_constraints_on_unimplemented_names.ca.der",
    "tests/tls_server_certs/reject_constraints_on_unimplemented_names.ee.der",
    "tests/tls_server_certs/wildcard_san_accepted_if_in_subtree.ca.der",
    "tests/tls_server_certs/wildcard_san_accepted_if_in_subtree.ee.der",
    "tests/tls_server_certs/wildcard_san_rejected_if_in_excluded_subtree.ca.der",
    "tests/tls_server_certs/wildcard_san_rejected_if_in_excluded_subtree.ee.der",
    "tests/wpt/ca.der",
    "tests/wpt/ee.der",
]
