[package]
name = "terad"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
async-nats = { workspace = true }
sysinfo = { workspace = true }
portable-pty = { workspace = true }
futures = { workspace = true }
bollard = { workspace = true }
zbus = { workspace = true }
config = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
exn = "0.3"
shared-types = { path = "../shared-types" }
ractor = { workspace = true }
connectrpc = { workspace = true }
buffa = { workspace = true }
buffa-types = { workspace = true }
serde = { workspace = true }

[build-dependencies]
connectrpc-build = { workspace = true }
