extra_srcs = [
    "tests/ecdsa/private_ecdsa_key.pem",
    "tests/ecdsa/private_ecdsa_key.pk8",
    "tests/ecdsa/private_jwtio_pkcs8.pem",
    "tests/ecdsa/public_ecdsa_key.pem",
    "tests/ecdsa/public_ecdsa_key.pk8",
    "tests/ecdsa/public_jwtio.pem",
    "tests/eddsa/private_ed25519_key.pem",
    "tests/eddsa/private_ed25519_key.pk8",
    "tests/eddsa/public_ed25519_key.pem",
    "tests/eddsa/public_ed25519_key.pk8",
    "tests/header/cert_chain.json",
    "tests/rsa/certificate_jwtio.crt",
    "tests/rsa/certificate_rsa_key_pkcs1.crt",
    "tests/rsa/certificate_rsa_key_pkcs8.crt",
    "tests/rsa/private_jwtio.pem",
    "tests/rsa/private_rsa_key.der",
    "tests/rsa/private_rsa_key_pkcs1.pem",
    "tests/rsa/private_rsa_key_pkcs8.pem",
    "tests/rsa/public_jwtio.pem",
    "tests/rsa/public_rsa_key.der",
    "tests/rsa/public_rsa_key_pkcs1.pem",
    "tests/rsa/public_rsa_key_pkcs8.pem",
]
